---
title: "Final Project: Summary Statistic"
author: "Samara O & Will C"
subtitle: "MGSC 310 Final Project: Summary Statistic"
output:
  html_document:
    df_print: paged
  html_notebook: default
---

```{r setup, include=FALSE}

# Please leave this code chunk as is. It makes some slight formatting changes to alter the output to be more aesthetically pleasing. 

library(knitr)

# Change the number in set seed to your own favorite number
set.seed(1818)
options(width=70)
options(scipen=99)


# this sets text outputted in code chunks to small
opts_chunk$set(tidy.opts=list(width.wrap=50),tidy=TRUE, size = "vsmall")  
opts_chunk$set(message = FALSE,                                          
               warning = FALSE,
               # "caching" stores objects in code chunks and only rewrites if you change things
               cache = FALSE,                               
               # automatically downloads dependency files
               autodep = TRUE,
               # 
               cache.comments = FALSE,
               # 
               collapse = TRUE,
               # change fig.width and fig.height to change the code height and width by default
               fig.width = 5.5,  
               fig.height = 4.5,
               fig.align='center')


```

```{r setup-2}

# Always print this out before your assignment
sessionInfo()
getwd()

```


<!-- ### start answering your problem set here -->
<!-- You may export your homework in either html or pdf, with the former usually being easier. 
     To export or compile your Rmd file: click above on 'Knit' then 'Knit to HTML' -->
<!-- Be sure to submit both your .Rmd file and the compiled .html or .pdf file for full credit -->


```{r setup-3}

# load all your libraries in this chunk 
library('tidyverse')
library('vtable')
# note, do not run install.packages() inside a code chunk. install them in the console outside of a code chunk. 

```



## Part 1: Data Loading and Summary Stats

1a) Loading Data. 
```{r}

library('tidyverse')
options(scipen = 50)
set.seed(1861)
setwd("~/downloads")
unicorns <- read_csv("unicorn_clean.csv") 

head(unicorns)

```


1b) Cleaning Data

```{r}
library('dplyr')
library('tidyverse')
library('ggrepel')
library('forcats')
library('rsample')
library('plotROC')
colnames(unicorns)[3] <- "valuation"
colnames(unicorns)[4] <- "date"
colnames(unicorns)[8] <- "investor1"
colnames(unicorns)[9] <- "investor2"
colnames(unicorns)[10] <- "investor3"
colnames(unicorns)[11] <- "investor4"


unicorns <-
  unicorns %>%
  mutate(City = 
           as_factor(City),
         Country = as_factor(Country),
         Industry = as_factor(Industry),
         investor1 = as_factor(investor1),
         investor2 = as_factor(investor2),
         investor3 = as_factor(investor3),
         investor4 = as_factor(investor4)
         )

  
glimpse(unicorns)

```

3a) Summary Stats

```{r}

#install.packages('vtable')
library('vtable')
st(unicorns)

```




## Part 2: Final Project: Models

2a) Plot #1


```{r}

library('ggplot2')
ggplot(data = unicorns, aes(x = valuation, y= Industry)) + geom_point() + geom_smooth()

```


2b) Plot #2


```{r}

ggplot(data = unicorns, aes(x = valuation, y= Country)) + geom_point() + geom_smooth()

```


2c) Plot #3


```{r}

ggplot(data = unicorns, aes(x = valuation, y = Industry)) + 
  geom_point() + 
  stat_summary(fun = "mean", color = "red", size = 1) +
  theme_bw()

```


